export const cyberTheme = {
  colors: {
    background:    '#06080F',
    surface:       '#0D1117',
    surfaceHigh:   '#161B27',
    surfaceSoft:   '#1C2333',
    textPrimary:   '#F0F6FF',
    textSecondary: '#94A3B8',
    textMuted:     '#4A5568',
    accent:        '#00D4FF',
    accentViolet:  '#7B5CF0',
    accentGold:    '#F7B731',
    accentGreen:   '#22C55E',
    accentPink:    '#F472B6',
    border:        '#1E2A3A',
    borderGlow:    '#00D4FF44',
    danger:        '#FF4D6D',
    dangerSoft:    '#FF4D6D22',
    overlay:       'rgba(6,8,15,0.88)',
  },
  spacing: {
    outer:     22,
    section:   16,
    cardInner: 14,
  },
  radius: {
    sm: 8,
    md: 14,
    lg: 20,
    xl: 28,
  },
  shadow: {
    cyan: {
      shadowColor: '#00D4FF',
      shadowOpacity: 0.4,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: 0},
      elevation: 14,
    },
    violet: {
      shadowColor: '#7B5CF0',
      shadowOpacity: 0.45,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: 0},
      elevation: 14,
    },
    gold: {
      shadowColor: '#F7B731',
      shadowOpacity: 0.35,
      shadowRadius: 14,
      shadowOffset: {width: 0, height: 0},
      elevation: 10,
    },
    // backward compat alias
    glow: {
      shadowColor: '#00D4FF',
      shadowOpacity: 0.4,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: 0},
      elevation: 14,
    },
  },
};
